spring:
  datasource:
    url: jdbc:mysql://localhost:3002/spring_sandbox_jpa_test
    username: spring_sandbox_jpa
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always
