spring:
  datasource:
    url: jdbc:mysql://localhost:3002/spring_sandbox_jpa_dev
    username: spring_sandbox_jpa
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  # pretty print for sql logs
  jpa:
    properties:
      hibernate:
        format_sql: true

# logs sql statements
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
          EnumType: TRACE
